name: Generate Contribution Snake

on:
  schedule:
    # Berjalan otomatis setiap 12 jam (jam 00:00 & 12:00 UTC)
    - cron: "0 */12 * * *"
  
  # Bisa ditrigger manual lewat tab Actions
  workflow_dispatch:
  
  # Otomatis jalan saat ada push ke main
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            public/github-contribution-grid-snake.svg
            public/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
